In [1]:
import numpy as np

# Tạo mảng 3x3 với giá trị ngẫu nhiên từ 0 đến 20
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên:")
print(arr)

# Kiểm tra tất cả phần tử khác 0
result = np.all(arr != 0)

print("\nTất cả phần tử khác 0 hay không?")
print(result)

Mảng ngẫu nhiên:
[[19  3 20]
 [ 7 15  2]
 [ 5 10 19]]

Tất cả phần tử khác 0 hay không?
True


In [2]:
import numpy as np

# Tạo mảng 3x3 với giá trị ngẫu nhiên từ 0 đến 20
arr = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên:")
print(arr)

# Kiểm tra có tồn tại ít nhất 1 phần tử khác 0 không
result = np.any(arr != 0)

print("\nCó tồn tại phần tử khác 0 không?")
print(result)

Mảng ngẫu nhiên:
[[ 9  5  1]
 [ 2 14 20]
 [13  5  9]]

Có tồn tại phần tử khác 0 không?
True


In [3]:
# =========================
# BÀI 3 - CELL 1: 1D ARRAY
# So sánh 2 mảng 1 chiều
# =========================

import numpy as np

a = np.array([1, 5, 3, 8, 2])
b = np.array([2, 5, 1, 7, 4])

print("Mảng a:", a)
print("Mảng b:", b)

print("\n a > b:", np.greater(a, b))
print(" a >= b:", np.greater_equal(a, b))
print(" a < b:", np.less(a, b))
print(" a <= b:", np.less_equal(a, b))

Mảng a: [1 5 3 8 2]
Mảng b: [2 5 1 7 4]

 a > b: [False False  True  True False]
 a >= b: [False  True  True  True False]
 a < b: [ True False False False  True]
 a <= b: [ True  True False False  True]


In [4]:
# =========================
# BÀI 3 - CELL 2: 2D ARRAY
# So sánh 2 mảng 2 chiều
# =========================

import numpy as np

a = np.array([[1, 4, 7],
              [3, 6, 9],
              [2, 5, 8]])

b = np.array([[2, 4, 6],
              [1, 7, 9],
              [3, 5, 7]])

print("Mảng a:\n", a)
print("\nMảng b:\n", b)

print("\n a > b:\n", np.greater(a, b))
print("\n a >= b:\n", np.greater_equal(a, b))
print("\n a < b:\n", np.less(a, b))
print("\n a <= b:\n", np.less_equal(a, b))

Mảng a:
 [[1 4 7]
 [3 6 9]
 [2 5 8]]

Mảng b:
 [[2 4 6]
 [1 7 9]
 [3 5 7]]

 a > b:
 [[False False  True]
 [ True False False]
 [False False  True]]

 a >= b:
 [[False  True  True]
 [ True False  True]
 [False  True  True]]

 a < b:
 [[ True False False]
 [False  True False]
 [ True False False]]

 a <= b:
 [[ True  True False]
 [False  True  True]
 [ True  True False]]


In [5]:
# =========================
# BÀI 4: TẠO MẢNG CƠ BẢN
# 10 số 1, 10 số 0, 10 số 5
# =========================

import numpy as np

# Tạo từng phần
ones = np.ones(10)
zeros = np.zeros(10)
fives = np.full(10, 5)

# Ghép lại thành 1 mảng
arr = np.concatenate((ones, zeros, fives))

print("Mảng ban đầu:")
print(arr)

Mảng ban đầu:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [6]:
# =========================
# BÀI 5: MẢNG SỐ CHẴN 30 → 70
# =========================

import numpy as np

# Tạo mảng từ 30 đến 70 (bao gồm 70)
arr = np.arange(30, 71)

# Lọc số chẵn
even_arr = arr[arr % 2 == 0]

print("Mảng ban đầu:")
print(arr)

print("\nMảng số chẵn từ 30 đến 70:")
print(even_arr)

Mảng ban đầu:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]

Mảng số chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [7]:
# =========================
# BÀI 6: MA TRẬN ĐƠN VỊ 3x3
# =========================

import numpy as np

# Tạo ma trận đơn vị 3x3
matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# =========================
# BÀI 7: MẢNG 10 PHẦN TỬ (15 → 55)
# IN TRỪ ĐẦU VÀ CUỐI
# =========================

import numpy as np

# Tạo mảng 10 phần tử trong khoảng [15, 55]
arr = np.random.randint(15, 56, size=10)

print("Mảng ban đầu:")
print(arr)

# Lấy các phần tử trừ đầu và cuối
result = arr[1:-1]

print("\nCác phần tử (trừ đầu và cuối):")
print(result)

Mảng ban đầu:
[54 40 44 26 51 39 53 31 44 35]

Các phần tử (trừ đầu và cuối):
[40 44 26 51 39 53 31 44]


In [9]:
# =========================
# BÀI 8: ĐỔI DẤU PHẦN TỬ
# (9 ≤ x ≤ 15)
# =========================

import numpy as np

# Tạo mảng 20 phần tử trong khoảng [0, 20]
arr = np.random.randint(0, 21, size=20)

print("Mảng ban đầu:")
print(arr)

# Điều kiện các số trong khoảng [9, 15]
mask = (arr >= 9) & (arr <= 15)

# Đổi dấu các phần tử thỏa điều kiện
arr[mask] = -arr[mask]

print("\nMảng sau khi đổi dấu (9 → 15):")
print(arr)

Mảng ban đầu:
[20  2  5  3 11 20 12  9  9 11 20 20  8 10 18  5  2 19  3 16]

Mảng sau khi đổi dấu (9 → 15):
[ 20   2   5   3 -11  20 -12  -9  -9 -11  20  20   8 -10  18   5   2  19
   3  16]


In [10]:
# =========================
# BÀI 9: MA TRẬN 3x4
# GIÁ TRỊ TRONG [10, 21]
# =========================

import numpy as np

# Tạo ma trận 3x4 với giá trị ngẫu nhiên từ 10 đến 21
matrix = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4:")
print(matrix)

Ma trận 3x4:
[[16 16 10 19]
 [12 11 20 16]
 [14 20 12 19]]


In [11]:
# =========================
# BÀI 10: MA TRẬN 10x10
# BIÊN = 1, BÊN TRONG = 0
# =========================

import numpy as np

# Tạo ma trận 10x10 toàn số 0
matrix = np.zeros((10, 10), dtype=int)

# Gán giá trị 1 cho các phần tử ở biên
matrix[0, :] = 1        # hàng đầu
matrix[-1, :] = 1       # hàng cuối
matrix[:, 0] = 1        # cột đầu
matrix[:, -1] = 1       # cột cuối

print("Ma trận 10x10:")
print(matrix)

Ma trận 10x10:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [12]:
# =========================
# BÀI 11: MA TRẬN 5x5
# ĐƯỜNG CHÉO CHÍNH = 1,2,3,4,5
# =========================

import numpy as np

# Tạo vector giá trị cho đường chéo chính
values = np.array([1, 2, 3, 4, 5])

# Tạo ma trận với đường chéo chính
matrix = np.diag(values)

print("Ma trận 5x5:")
print(matrix)

Ma trận 5x5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [13]:
# =========================
# BÀI 12: MẢNG 3x3x3
# TÍNH TỔNG THEO DÒNG & CỘT
# =========================

import numpy as np

# Tạo mảng 3x3x3 với giá trị ngẫu nhiên
arr = np.random.randint(1, 10, size=(3, 3, 3))

print("Mảng 3x3x3:")
print(arr)

Mảng 3x3x3:
[[[6 9 3]
  [3 6 8]
  [9 4 2]]

 [[9 3 8]
  [2 6 3]
  [9 8 7]]

 [[4 5 2]
  [3 7 6]
  [7 6 9]]]


In [14]:
# =========================
# BÀI 13: INNER PRODUCT
# 2 VECTOR 10 PHẦN TỬ
# =========================

import numpy as np

# Tạo 2 vector ngẫu nhiên 10 phần tử
a = np.random.randint(1, 10, size=10)
b = np.random.randint(1, 10, size=10)

print("Vector a:", a)
print("Vector b:", b)

# Tính inner product
result = np.dot(a, b)

print("\nInner product (a · b):", result)

Vector a: [6 9 5 8 3 1 8 1 3 1]
Vector b: [3 3 8 8 6 6 4 4 7 7]

Inner product (a · b): 237


In [15]:
# =========================
# BÀI 14: MA TRẬN + VECTOR
# A (4x3) + y (3 phần tử)
# =========================

import numpy as np

# Tạo ma trận A kích thước 4x3
A = np.random.randint(1, 10, size=(4, 3))

# Tạo vector y gồm 3 phần tử
y = np.random.randint(1, 10, size=3)

print("Ma trận A:")
print(A)

print("\nVector y:")
print(y)

# Cộng vector y vào từng dòng của A (broadcasting)
result = A + y

print("\nKết quả A + y:")
print(result)

Ma trận A:
[[7 4 6]
 [2 6 3]
 [3 9 2]
 [9 7 3]]

Vector y:
[5 6 4]

Kết quả A + y:
[[12 10 10]
 [ 7 12  7]
 [ 8 15  6]
 [14 13  7]]


In [16]:
# =========================
# BÀI 15: PANDAS SERIES
# +, -, *, /
# =========================

import pandas as pd

# Tạo 2 Series
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:")
print(s1)

print("\nSeries 2:")
print(s2)

# Các phép toán
print("\nCộng:")
print(s1 + s2)

print("\nTrừ:")
print(s1 - s2)

print("\nNhân:")
print(s1 * s2)

print("\nChia:")
print(s1 / s2)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0     1
1     3
2     5
3     7
4    10
dtype: int64

Cộng:
0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ:
0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [17]:
# =========================
# BÀI 16: DATAFRAME → SERIES
# CỘT ĐẦU TIÊN
# =========================

import pandas as pd

# Tạo DataFrame mẫu
df = pd.DataFrame({
    "A": [10, 20, 30, 40],
    "B": [1, 2, 3, 4],
    "C": [5, 6, 7, 8]
})

print("DataFrame:")
print(df)

# Lấy cột đầu tiên thành Series
# (ix đã bị deprecated nên dùng iloc thay thế)
first_col = df.iloc[:, 0]

print("\nCột đầu tiên (Series):")
print(first_col)

DataFrame:
    A  B  C
0  10  1  5
1  20  2  6
2  30  3  7
3  40  4  8

Cột đầu tiên (Series):
0    10
1    20
2    30
3    40
Name: A, dtype: int64


# =========================
# BÀI 17: SẮP XẾP DATAFRAME NGẪU NHIÊN
# =========================

In [18]:
import pandas as pd
import numpy as np

# Tạo DataFrame 4x3 với giá trị ngẫu nhiên
df = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=list('ABC'))

print("DataFrame ban đầu:")
print(df)

# Sắp xếp DataFrame theo cột 'A'
sorted_df = df.sort_values(by='A')

print("\nDataFrame sau khi sắp xếp theo cột 'A':")
print(sorted_df)

DataFrame ban đầu:
    A   B   C
0  62  77  57
1  16   7  46
2  44   3  38
3  85   1   1

DataFrame sau khi sắp xếp theo cột 'A':
    A   B   C
1  16   7  46
2  44   3  38
0  62  77  57
3  85   1   1


# =========================
# BÀI 18: THAY ĐỔI INDEX CỦA SERIES
# =========================

In [19]:
import pandas as pd

# Tạo một Series
sr = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

print("Series ban đầu:")
print(sr)

# Tạo index mới
new_index = ['e', 'd', 'c', 'b', 'a', 'f']

# Thay đổi index của Series bằng reindex
reindexed_sr = sr.reindex(new_index)

print("\nSeries sau khi thay đổi index:")
print(reindexed_sr)

Series ban đầu:
a    10
b    20
c    30
d    40
e    50
dtype: int64

Series sau khi thay đổi index:
e    50.0
d    40.0
c    30.0
b    20.0
a    10.0
f     NaN
dtype: float64


# =========================
# BÀI 19: TÌM PHẦN TỬ KHÔNG CÓ TRONG SERIES KHÁC
# =========================

In [20]:
import pandas as pd

# Tạo Series sr1 và sr2
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("Series sr1:")
print(sr1)

print("\nSeries sr2:")
print(sr2)

# Tìm các phần tử trong sr1 mà không có trong sr2
# Sử dụng ~ (NOT) với isin()
items_not_in_sr2 = sr1[~sr1.isin(sr2)]

print("\nCác phần tử của sr1 không có trong sr2:")
print(items_not_in_sr2)

Series sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Series sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Các phần tử của sr1 không có trong sr2:
0    1
2    3
4    5
dtype: int64


# =========================
# BÀI 20: NUMPY UNION1D, INTERSECT1D TRÊN SERIES
# =========================

In [21]:
import numpy as np
import pandas as pd

# Tạo 2 Series ngẫu nhiên với 20 phần tử
x = pd.Series(np.random.randint(0, 20, size=20))
y = pd.Series(np.random.randint(10, 30, size=20))

print("Series x:")
print(x)

print("\nSeries y:")
print(y)

# Tìm hợp (union) của hai Series
union_xy = np.union1d(x, y)

print("\nHợp của x và y (union1d):")
print(union_xy)

# Tìm giao (intersection) của hai Series
intersect_xy = np.intersect1d(x, y)

print("\nGiao của x và y (intersect1d):")
print(intersect_xy)

Series x:
0     14
1      2
2     14
3     18
4      1
5     11
6      7
7     11
8      4
9     14
10    19
11    18
12    13
13     4
14    16
15     1
16     3
17     8
18    18
19    18
dtype: int64

Series y:
0     23
1     16
2     21
3     20
4     26
5     19
6     14
7     13
8     26
9     14
10    17
11    28
12    27
13    15
14    28
15    22
16    12
17    21
18    11
19    20
dtype: int64

Hợp của x và y (union1d):
[ 1  2  3  4  7  8 11 12 13 14 15 16 17 18 19 20 21 22 23 26 27 28]

Giao của x và y (intersect1d):
[11 13 14 16 19]


In [22]:
import pandas as pd
import string

# Tạo Series x (số nguyên từ 0 đến 9)
x = pd.Series(range(10))

# Tạo Series y (chữ cái từ 'p' đến 'y')
y = pd.Series(list(string.ascii_lowercase[15:25])) # 'p' is the 16th letter (index 15), 'y' is the 25th letter

print("Series x:")
print(x)

print("\nSeries y:")
print(y)

# Thêm Series y vào Series x theo chiều dọc (vertical)
# Sử dụng pd.concat
vertical_concat = pd.concat([x, y])

print("\nKết quả nối dọc (vertical concat):")
print(vertical_concat)

# Thêm Series y vào Series x theo chiều ngang (horizontal)
# Sử dụng pd.concat với axis=1
horizontal_concat = pd.concat([x, y], axis=1)

print("\nKết quả nối ngang (horizontal concat):")
print(horizontal_concat)

Series x:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

Series y:
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết quả nối dọc (vertical concat):
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Kết quả nối ngang (horizontal concat):
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [23]:
# =========================
# BÀI 22: TẠO DATAFRAME
# =========================

import numpy as np
import pandas as pd

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
             'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],

    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],

    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],

    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a','b','c','d','e','f','g','h','i','j']

df = pd.DataFrame(exam_data, index=labels)

print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [24]:
# =========================
# BÀI 23: 3 DÒNG ĐẦU
# =========================

print(df.head(3))

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [25]:
# =========================
# BÀI 24: CHỌN CỘT
# =========================

print(df[['name', 'score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [26]:
# =========================
# BÀI 25: FILTER attempts > 2
# =========================

print(df[df['attempts'] > 2])

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


In [27]:
# =========================
# BÀI 26: SHAPE
# =========================

print("Số dòng, số cột:", df.shape)

Số dòng, số cột: (10, 4)


In [28]:
# =========================
# BÀI 27: SCORE = NaN
# =========================

print(df[df['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [29]:
# =========================
# BÀI 28: BETWEEN
# =========================

print(df[df['score'].between(15, 20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


In [30]:
# =========================
# BÀI 29: NHIỀU ĐIỀU KIỆN
# =========================

print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

      name  score  attempts qualify
f  Michael   20.0         3     yes


In [32]:
# =========================
# BÀI 30: LOC UPDATE
# =========================

df.loc['d', 'score'] = 19

print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   19.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


# =========================
# BÀI 23: 3 DÒNG ĐẦU
# =========================

print(df.head(3))